In [8]:
from dateutil import parser

t1 = '22/May/04'
t2 = 'May/07/22'
t3 = '2024-07-24 18:15:07'

d1 = parser.parse(t1).date()
print(d1)

d2 = parser.parse(t2)
print(d2)

d3 = parser.parse(t3)
print(d3)

d3 = parser.parse(t3).time()
print(d3)

2004-05-22
2022-05-07 00:00:00
2024-07-24 18:15:07
18:15:07


In [10]:
time = '18:57:22'

t = parser.parse(time)   #automatiskai prideda sios dienos data
print(t)

2024-07-24 18:57:22


In [11]:
#numpy modulis 

l = [1,2,3]
f = [0.2,0.3,0.4]

# c = l*f

c = []
for li, fi in zip(l,f):
    c.append(li*fi)
    
print(c)

[0.2, 0.6, 1.2000000000000002]


In [12]:
import numpy as np

In [13]:
f = []
for i in range(11):
    f.append(i)
print(f)

# ats = f * 0.2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [14]:
f = np.arange(0,11)  #pvz numpy 
print(f)  # nupy atvaizduoja nenaudojant kableliu (matome kad pasikeite duomenu tipas)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [16]:
f[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
c = f *0.2
print(c)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [20]:
f = np.asarray([1,2,3])    #skirta konvertuoti sarasus/eilutes i numpy masyvus 
l = np.asarray([0.1,0.2,0.3])[:len(f)] #operacija apkarpo ilgesni sarasa iki trumpesnio kad butu vienodi 
               
a= f*l   #elementu kiekis privalo buti vienodas
print(a)

[0.1 0.4 0.9]


In [23]:
np.linspace(0,10, 11)  #vienas sugeneruoja 50 skaiciu (default nustatymas)






array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [24]:
s = [1,2,3]

np.mean(s)  

np.float64(2.0)

In [25]:
s = [1,2,3]

np.average(s)  

np.float64(2.0)

In [26]:
w = np.random.rand(11) #grazina atsitiktinius skaiciu 11 
print(w)

[0.77726409 0.8505592  0.25164713 0.14097933 0.41055    0.26187512
 0.17814987 0.14835873 0.3628632  0.37595985 0.52535914]


In [28]:
c = np.random.randint(1,10,11)
print(c)   #sugeneruoja atsitiktiniu skaiciu masyva 0-10


[5 5 3 3 5 4 2 4 8 6 5]


In [32]:
print(np.average(c))
print(np.mean(c))
print(np.average(c, weights= w))  #pvz su svoriais 


4.545454545454546
4.545454545454546
4.9380453300438


In [40]:
np.median(c)   #mediana 


np.float64(5.0)

In [44]:
f = '../../DATA/fpc.csv'  #2 kartus einame i virsu per failus 
ft = np.loadtxt(f, delimiter=',', skiprows=1)  #skiprows atmeta eilutes nuo virsaus pagal skaiciu #delimiter - rodo koks yra skiriamasis zenklas 
# print(ft)
c1,c2,c3,c4,c5 = zip(*ft)
print(c1)


(np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0), np.float64(16.0), np.float64(17.0), np.float64(18.0), np.float64(19.0), np.float64(20.0), np.float64(21.0), np.float64(22.0), np.float64(23.0), np.float64(24.0), np.float64(25.0), np.float64(26.0), np.float64(27.0), np.float64(28.0), np.float64(29.0), np.float64(30.0))


In [45]:
c1,c2,c3,c4,c5 = np.transpose(ft)  #pakeicia i eilute (numpy formatas islieka)
print(c1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]


In [66]:
#nuskaitykyte Table1.dat, ir suraskite:
#  stulpeliuose esančių skaičių vidurkį, medianą
# suraskite sandaugą antro stlpelio su trečiuoju, tada gauto atsakymo vidurkį.
# Suapvalinkite visus atsakymus iki 2-jų ženklų poo kablelio

x = '../../DATA/Table1.dat'  #2 kartus einame i virsu per failus 

ft = np.loadtxt(x, delimiter=';', skiprows=1)  #skiprows atmeta eilutes nuo virsaus pagal skaiciu #delimiter - rodo koks yra skiriamasis zenklas 
# print(ft)
print(np.average(ft))

c1,c2,c3 = np.transpose(ft)
d1 = c2 * c3

print(d1)

vidurkis = np.average(d1)

print(vidurkis)

# suapvalintas = np.round(vidurkis, 2)

print(suapvalintas)


5.23964388384234
[-0.9645133  -0.21510477 -0.90817357 -0.2661279  -0.18706099 -0.10427351
 -0.25384732  0.15733513  0.21059587  0.10330919  0.02279286 -0.1544075
 -0.08471563  0.5675087  -0.46670442  0.88842748 -0.42068381 -0.05742485
  0.04100096  0.18725263  0.70027375 -0.20595805  0.80601812 -0.60959484
  1.01968247  0.29587431  1.77129302 -0.46115595  0.76721917  0.14283317]
0.07738901370414458
0.08


In [ ]:
# • Parašyti klasę TxtReader skirtą tekstinio failo iš dviejų
# stulpelių nuskaitymui . Esant poreikiui, inicializacijos metu
# galima nurodyti stulpelių skirtuką, ar konvertuoti pirmąjį
# stulpelį į datą (datetime objektą), kiek eilučių praleisti nuo
# failo pradžios. Jei failas turi daugiau nei du stulpelius - galima
# nurodyti, kuris stulpelis konkrečiai yra x, o kuris y. Atributai x
# ir y - privatūs.
# Pridėkite motdus, kurie leistų surasti stulpelio y vidurkį, medianą, maksimumą, minimumą

class TxtReader: 
    def __init__(self, filename, delimiter=','):
        self.filename = filename
        self.delimiter = delimiter
        
