In [1]:
# .isnumeric(), .isalpha() - a-z
txt = 'Labs, šiandien yra 24 liepos, 7-to mėnesio diena'
# parašyti funkciją, skirtą naudoti su map()
# ir gaukite sąrašą, kur, jei simbolis duotąjame tekste buvo skaičius - rašote 'Skaičius;,
#  o jei tai buvo raidė - rašote 'S', o jei tai spec. simbolis - rašote 42 (skaičių)

In [2]:
s = [1,2,3]

def f(x):
    return x*2

a = list(map(f, s))
print(a)

[2, 4, 6]


In [3]:
r = ['a', 'b', 'c']

def f(x):
    return x.upper()

print(list(map(f, r)))

['A', 'B', 'C']


In [4]:
a = list(map(lambda x: x*2, s))
print(a)

[2, 4, 6]


In [5]:
from dateutil import parser

In [10]:
t1 = '22/May/04'
t2 = 'May/07/22'
t3 = '2024-07-24 18:15:07'

d1 = parser.parse(t1).date()
print(d1)
d2 = parser.parse(t2)
print(d2)
d3 = parser.parse(t3).time()
print(d3)

2004-05-22
2022-05-07 00:00:00
18:15:07


In [11]:
time = '18:57:22'
t = parser.parse(time)
print(t)

2024-07-24 18:57:22


In [13]:
l = [1,2,3]
f = [0.2, 0.3, 0.4, 0.5]
#  c = l * f
c = []
for li, fi in zip(l, f):
    c.append(li*fi)

print(c)

[0.2, 0.6, 1.2000000000000002]


In [14]:
import numpy as np

In [15]:
f = []
for i in range(11):
    f.append(i)
print(f)
#  ats = f * 0.2 ?

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [16]:
f = np.arange(0, 11)
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [18]:
f[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
c = f * 0.2
print(c)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [25]:
f = np.asarray([1,2,3])
l = np.asarray([0.1,0.2,0.3, 0.5, 0.7])[:len(f)]

a = f*l
print(a)

[0.1 0.4 0.9]


In [30]:
np.round(np.linspace(0,10, 11, endpoint=False), 2)


array([0.  , 0.91, 1.82, 2.73, 3.64, 4.55, 5.45, 6.36, 7.27, 8.18, 9.09])

In [31]:
s = [1,2,3]
np.mean(s)

2.0

In [32]:
np.average(s)

2.0

In [33]:
w = np.random.rand(11)
print(w)

[0.09463819 0.18376758 0.38408447 0.40308669 0.94511121 0.50892253
 0.26153074 0.96997118 0.72614117 0.03582235 0.83145838]


In [34]:
c = np.random.randint(1,10, 11)
print(c)

[5 8 5 7 4 2 6 8 7 4 5]


In [36]:
print(np.average(c))
print(np.mean(c))
print(np.average(c, weights=w))

5.545454545454546
5.545454545454546
5.649916589949419


In [37]:
np.median(c)

5.0

In [42]:
f = '../DATA/fpc.csv'
ft = np.loadtxt(f, delimiter=',', skiprows=1)
# skaidymas į stulpelius:
c1,c2,c3,c4,c5 = zip(*ft)
print(c1)

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0)


In [43]:
c1,c2,c3,c4,c5 = np.transpose(ft)
print(c1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]


In [ ]:
#nuskaitykyte Table1.dat, ir suraskite:
#  stulpeliuose esančių skaičių vidurkį, medianą
# suraskite sandaugą antro stlpelio su trečiuoju, tada gauto atsakymo vidurkį.
# Suapvalinkite visus atsakymus iki 2-jų ženklų poo kablelio


In [ ]:
#  Parašyti klasę TxtReader skirtą tekstinio failo iš dviejų
# stulpelių nuskaitymui . Esant poreikiui, inicializacijos metu
# galima nurodyti stulpelių skirtuką, ar konvertuoti pirmąjį
# stulpelį į datą (datetime objektą), kiek eilučių praleisti nuo
# failo pradžios. Jei failas turi daugiau nei du stulpelius - galima
# nurodyti, kuris stulpelis konkrečiai yra x, o kuris y. Atributai x
# ir y - privatūs.
# Pridėkite motdus, kurie leistų surasti stulpelio y vidurkį, medianą, maksimumą, minimumą