In [2]:
print('2024-07-24\n13 paskaita')

2024-07-24
13 paskaita


In [6]:
# .isnumeric(), .isalpha() - a-z
txt = 'Labs, šiandien yra 24 liepos, 7-to mėnesio diena'
txt = 'A4= x'
# parašyti funkciją, skirtą naudoti su map()
# ir gaukite sąrašą, kur, jei simbolis duotąjame tekste buvo skaičius - rašote 'Skaičius;,
# o jei tai buvo raidė - rašote 'S', o jei tai spec. simbolis - rašote 42 (skaičių)

def eilute(t):
    ats = list(map(lambda x: "skaicius" if x.isnumeric() else 'S' if x.isalpha() else 42, t))
    return ats

eilute(txt)

['S', 'skaicius', 42, 42, 'S']

In [11]:
from dateutil import parser

d=[]
d.append('2024-06-17')
d.append('7/8/9')
d.append('7.8.9')
d.append('1-2-3')
d.append('10/mar/11')

for dd in d:
    print(parser.parse(dd))

2024-06-17 00:00:00
2009-07-08 00:00:00
2009-07-08 00:00:00
2003-01-02 00:00:00
2011-03-10 00:00:00


In [41]:
import numpy as np

f=[]
for i in range (11):
    f.append(i)
print(f)
print(f*2)

g=np.arange(0,11)
print(g)
print(g*2)

h=np.arange(10,15)
m=np.arange(15,20)

print(m,'m')
print(h,'h')
print(m*h,'m*h')
print(m/h,'m/h')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[15 16 17 18 19] m
[10 11 12 13 14] h
[150 176 204 234 266] m*h
[1.5        1.45454545 1.41666667 1.38461538 1.35714286] m/h


In [42]:
print(np.linspace(1,10,5))
print(np.linspace(1,10,7))

p=np.random.rand(6)
print(p)
print(np.average(p))
print(np.mean(p))
print(np.median(p))

[ 1.    3.25  5.5   7.75 10.  ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[0.43317563 0.77840799 0.28991474 0.67607637 0.18694958 0.086229  ]
0.408458885925874
0.408458885925874
0.3615451866032599


In [53]:
r=np.loadtxt('../../DATA/fpc.csv',delimiter=',',skiprows=1)
print(r[0])
print(r[1])
print(r[2])
print()

s1,s2,s3,s4,s5=zip(*r)
print(s1)
print(s2)
print(s3)
print(s4)
print(s5)


[1.         0.14524176 1.27893738 0.96891242 0.24740396]
[ 2.          0.65124422 -0.22124983  0.87758256  0.47942554]
[3.         0.40350402 0.26072018 0.73168887 0.68163876]

(1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27.0, 28.0, 29.0, 30.0)
(0.1452417613699, 0.6512442209278, 0.4035040242722, 0.4132777648612, 0.5376411841046, 0.1291337706973, 0.1095216706458, 0.09160293026716, 0.4375391272162, 0.9592487370183, 0.9081051778975, 0.9680425954415, 0.2747224875965, 0.9395053829374, 0.02702508007502, 0.1085425346591, 0.4510075977325, 0.3480182621135, 0.7447402033832, 0.4360231445388, 0.9591874750078, 0.6777559523593, 0.3108400419198, 0.4439762905753, 0.279228458508, 0.1417351946639, 0.586848460719, 0.7415905076166, 0.04117579111077, 0.7625497651729)
(1.278937382525, -0.221249827056, 0.2607201762198, -0.639773669202, -1.289622965918, -0.5827399456765, -0.6255631311019, 0.4207626695444, 0