In [2]:
print('2024-07-24\n13 paskaita')

2024-07-24
13 paskaita


In [6]:
# .isnumeric(), .isalpha() - a-z
txt = 'Labs, šiandien yra 24 liepos, 7-to mėnesio diena'
txt = 'A4= x'
# parašyti funkciją, skirtą naudoti su map()
# ir gaukite sąrašą, kur, jei simbolis duotąjame tekste buvo skaičius - rašote 'Skaičius;,
# o jei tai buvo raidė - rašote 'S', o jei tai spec. simbolis - rašote 42 (skaičių)

def eilute(t):
    ats = list(map(lambda x: "skaicius" if x.isnumeric() else 'S' if x.isalpha() else 42, t))
    return ats

eilute(txt)

['S', 'skaicius', 42, 42, 'S']

In [11]:
from dateutil import parser

d=[]
d.append('2024-06-17')
d.append('7/8/9')
d.append('7.8.9')
d.append('1-2-3')
d.append('10/mar/11')

for dd in d:
    print(parser.parse(dd))

2024-06-17 00:00:00
2009-07-08 00:00:00
2009-07-08 00:00:00
2003-01-02 00:00:00
2011-03-10 00:00:00


In [25]:
import numpy as np

f=[]
for i in range (11):
    f.append(i)
print(f)
print(f*2)

g=np.arange(0,11)
print(g)
print(g*2)

h=np.arange(10,15)
m=np.arange(15,20)

print(m,'m')
print(h,'h')
print(m*h,'m*h')
print(m/h,'m/h')

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10 12 14 16 18 20]
[15 16 17 18 19] m
[10 11 12 13 14] h
[150 176 204 234 266] m*h
[1.5        1.45454545 1.41666667 1.38461538 1.35714286] m/h


In [37]:
print(np.linspace(1,10,5))
print(np.linspace(1,10,7))

p=np.random.rand(6)
print(p)
print(np.average(p))
print(np.mean(p))
print(np.median(p))

[ 1.    3.25  5.5   7.75 10.  ]
[ 1.   2.5  4.   5.5  7.   8.5 10. ]
[0.87759354 0.28714739 0.03664882 0.01169538 0.45925891 0.61200168]
0.3807242866344016
0.3807242866344016
0.37320315069019966


In [39]:
# r=np.loadtxt('../../DATA/fpc.csv')
# print(r)