In [1]:
# .isnumeric(), .isalpha() - a-z
txt = 'Labs, šiandien yra 24 liepos, 7-to mėnesio diena'
# parašyti funkciją, skirtą naudoti su map()
# ir gaukite sąrašą, kur, jei simbolis duotąjame tekste buvo skaičius - rašote 'Skaičius;,
#  o jei tai buvo raidė - rašote 'S', o jei tai spec. simbolis - rašote 42 (skaičių)

In [2]:
s = [1,2,3]

def f(x):
    return x*2

a = list(map(f, s))
print(a)

[2, 4, 6]


In [3]:
r = ['a', 'b', 'c']

def f(x):
    return x.upper()

print(list(map(f, r)))

['A', 'B', 'C']


In [4]:
a = list(map(lambda x: x*2, s))
print(a)

[2, 4, 6]


In [4]:
from dateutil import parser

In [5]:
t1 = '22/May/04'
t2 = 'May/07/22'
t3 = '2024-07-24 18:15:07'

d1 = parser.parse(t1).date()
print(d1)
d2 = parser.parse(t2)
print(d2)
d3 = parser.parse(t3).time()
print(d3)

2004-05-22
2022-05-07 00:00:00
18:15:07


In [6]:
time = '18:57:22'
t = parser.parse(time)
print(t)

2024-07-31 18:57:22


In [7]:
l = [1,2,3]
f = [0.2, 0.3, 0.4, 0.5]
#  c = l * f
c = []
for li, fi in zip(l, f):
    c.append(li*fi)

print(c)

[0.2, 0.6, 1.2000000000000002]


In [8]:
import numpy as np

In [9]:
f = []
for i in range(11):
    f.append(i)
print(f)
#  ats = f * 0.2 ?

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [10]:
f = np.arange(0, 11)
print(f)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [11]:
f[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
c = f * 0.2
print(c)

[0.  0.2 0.4 0.6 0.8 1.  1.2 1.4 1.6 1.8 2. ]


In [13]:
f = np.asarray([1,2,3])
l = np.asarray([0.1,0.2,0.3, 0.5, 0.7])[:len(f)]

a = f*l
print(a)

[0.1 0.4 0.9]


In [14]:
np.round(np.linspace(0,10, 11, endpoint=False), 2)


array([0.  , 0.91, 1.82, 2.73, 3.64, 4.55, 5.45, 6.36, 7.27, 8.18, 9.09])

In [15]:
s = [1,2,3]
np.mean(s)

np.float64(2.0)

In [16]:
np.average(s)

np.float64(2.0)

In [17]:
w = np.random.rand(11)
print(w)

[0.71329757 0.02436451 0.15352329 0.68490184 0.13059853 0.23267532
 0.67831383 0.08417563 0.1273843  0.17062405 0.84244797]


In [18]:
c = np.random.randint(1,10, 11)
print(c)

[9 9 9 9 9 3 3 1 1 6 2]


In [19]:
print(np.average(c))
print(np.mean(c))
print(np.average(c, weights=w))

5.545454545454546
5.545454545454546
5.468938371328212


In [20]:
print(np.median(c))

6.0


In [21]:
f = 'C:/Users/manta/OneDrive/Dokumentai/Python projektai/DataScienceNotebooks/Studentai/MantasD/DATA/fpc.csv'
ft = np.loadtxt(f, delimiter=',', skiprows=1)
# skaidymas į stulpelius:
c1,c2,c3,c4,c5 = zip(*ft)
print(c1,c2,c3,c4,c5,sep='\n\n')

(np.float64(1.0), np.float64(2.0), np.float64(3.0), np.float64(4.0), np.float64(5.0), np.float64(6.0), np.float64(7.0), np.float64(8.0), np.float64(9.0), np.float64(10.0), np.float64(11.0), np.float64(12.0), np.float64(13.0), np.float64(14.0), np.float64(15.0), np.float64(16.0), np.float64(17.0), np.float64(18.0), np.float64(19.0), np.float64(20.0), np.float64(21.0), np.float64(22.0), np.float64(23.0), np.float64(24.0), np.float64(25.0), np.float64(26.0), np.float64(27.0), np.float64(28.0), np.float64(29.0), np.float64(30.0))

(np.float64(0.1452417613699), np.float64(0.6512442209278), np.float64(0.4035040242722), np.float64(0.4132777648612), np.float64(0.5376411841046), np.float64(0.1291337706973), np.float64(0.1095216706458), np.float64(0.09160293026716), np.float64(0.4375391272162), np.float64(0.9592487370183), np.float64(0.9081051778975), np.float64(0.9680425954415), np.float64(0.2747224875965), np.float64(0.9395053829374), np.float64(0.02702508007502), np.float64(0.1085425346591), 

In [22]:
c1,c2,c3,c4,c5 = np.transpose(ft)
print(c1)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30.]


In [ ]:
#nuskaitykyte Table1.dat, ir suraskite:
#  stulpeliuose esančių skaičių vidurkį, medianą
# suraskite sandaugą antro stlpelio su trečiuoju, tada gauto atsakymo vidurkį.
# Suapvalinkite visus atsakymus iki 2-jų ženklų poo kablelio


In [ ]:
#  Parašyti klasę TxtReader skirtą tekstinio failo iš dviejų
# stulpelių nuskaitymui . Esant poreikiui, inicializacijos metu
# galima nurodyti stulpelių skirtuką, ar konvertuoti pirmąjį
# stulpelį į datą (datetime objektą), kiek eilučių praleisti nuo
# failo pradžios. Jei failas turi daugiau nei du stulpelius - galima
# nurodyti, kuris stulpelis konkrečiai yra x, o kuris y. Atributai x
# ir y - privatūs.
# Pridėkite motdus, kurie leistų surasti stulpelio y vidurkį, medianą, maksimumą, minimumą